services:
  app:
    container_name: 'selffastapi'
    build:
      dockerfile: ./Dockerfile
    command:
      - "make"
      - "run"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    networks:
      - mynet

  db:
    image: postgres:16.2
    container_name: 'db'
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: symon
      POSTGRES_DB: self_project
    ports:
      - "5432:5432"
    networks:
      - mynet

  redis:
    image: redis:alpine
    container_name: 'db'
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynet

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: 'zookeeper'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - mynet

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: 'kafka'
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - mynet

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  mynet:
    driver: bridge
    external: true